name: CI/CD
on:
  push:
    branches:
      - main
      - beta
      - renovate/**
  pull_request: null
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@d7a49f65845bc8ed726978e1790d7dd13cc9c0cf # v4.2.1
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@d7a49f65845bc8ed726978e1790d7dd13cc9c0cf # v4.2.1
  release:
    uses: vidavidorra/.github/.github/workflows/release.yml@d7a49f65845bc8ed726978e1790d7dd13cc9c0cf # v4.2.1
    needs:
      - lint-commit-messages
      - lint
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
